<Project>
  <PropertyGroup>
    <ProductShortName>PokerTrainer</ProductShortName>
    <ProductDisplayName>PokerTrainer Desktop</ProductDisplayName>
    <ProductRootNamespace>PokerTrainer</ProductRootNamespace>
    <ProductDataFolderName>PokerTrainer</ProductDataFolderName>
    <ProductEnvPrefix>POKERTRAINER</ProductEnvPrefix>
    <ProductVersion>1.0.0</ProductVersion>
    <ProductPackageVersion>1.0.0.0</ProductPackageVersion>
    <ProductPackageIdentityName>PokerTrainer.Desktop</ProductPackageIdentityName>
    <ProductPublisher>CN=PokerTrainerDevelopment</ProductPublisher>
    <ProductPublisherDisplayName>PokerTrainer Development</ProductPublisherDisplayName>
    <ProductPhoneProductId>a0139e04-45fa-4769-aef1-1cbb3d68976a</ProductPhoneProductId>
    <ProductPhonePublisherId>9fbac7b8-3a38-4fe4-a1d7-09eef90dd707</ProductPhonePublisherId>
    <DesktopExecutableName>PokerTrainer.Desktop</DesktopExecutableName>
    <RuntimeHostExecutableName>PokerTrainer.RuntimeHost</RuntimeHostExecutableName>
    <ApiExecutableName>PokerTrainer.Api</ApiExecutableName>
    <PostgresDatabaseName>poker_trainer</PostgresDatabaseName>
    <DockerNamePrefix>poker-trainer</DockerNamePrefix>
    <WebPackageName>poker-trainer.web</WebPackageName>
  </PropertyGroup>
</Project>