<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dotnet10Template.Domain\Dotnet10Template.Domain.csproj" />
    <ProjectReference Include="..\Dotnet10Template.Application\Dotnet10Template.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Configurations\" />
    <Folder Include="Data\Migrations\" />
    <Folder Include="Data\Seed\" />
    <Folder Include="Services\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
